### ISSUE TITLE
document execute configuration

### ISSUE THREAD

**Issue by fbrandt** [fbrandt/Ceva#11]
```
execute:
  instances:
    - metric: fixed
      value: foo
  imetrics:
    include:
      - fixed
  algorithms: false
  smetrics:
    exclude:
      - ocrash
```
