### ISSUE TITLE
Filter for instances to run 

### ISSUE THREAD

**Issue by fbrandt** [fbrandt/Ceva#4]
for an individual CEVA run I want to filter which instances should be run. Configurable by the calling ceva.yml like this:

```
execute:
  instances:
    - files:
        - a.txt
        - *hard*
    - metric: tags
      contains: [test_sml, test_big]
    - metric: type
      value: SAT
```
It should be possible to filter by instance name pattern and instance metrics values(=) and contains(LIKE %). Multiple filters should return only instances matching all filters.
